### ISSUE TITLE
Mac OS X portability errors

### ISSUE THREAD

**Issue by ChrisCummins** [ChrisCummins/labm8#12]
```
$ python2 ./setup.py test                                                                                                                           16:52:03
running test
Searching for nose
Best match: nose 1.3.7
Processing nose-1.3.7-py2.7.egg

Using /Users/cec/src/labm8/.eggs/nose-1.3.7-py2.7.egg
Searching for coverage
Best match: coverage 4.0a6
Processing coverage-4.0a6-py2.7-macosx-10.10-x86_64.egg

Using /Users/cec/src/labm8/.eggs/coverage-4.0a6-py2.7-macosx-10.10-x86_64.egg
running egg_info
writing requirements to labm8.egg-info/requires.txt
writing labm8.egg-info/PKG-INFO
writing top-level names to labm8.egg-info/top_level.txt
writing dependency_links to labm8.egg-info/dependency_links.txt
reading manifest file 'labm8.egg-info/SOURCES.txt'
writing manifest file 'labm8.egg-info/SOURCES.txt'
running build_ext
test_cache (tests.test_cache.TestCache) ... ok
test_json_cache (tests.test_cache.TestCache) ... ok
test_transient_cache (tests.test_cache.TestCache) ... ok
test_sha1_empty_str (tests.test_crypto.TestCrypto) ... ok
test_sha1_file_empty (tests.test_crypto.TestCrypto) ... ok
test_sha1_file_hello_world (tests.test_crypto.TestCrypto) ... ok
test_sha1_hello_world (tests.test_crypto.TestCrypto) ... ok
test_attach_detach (tests.test_db.TestDatabase) ... ok
test_close (tests.test_db.TestDatabase) ... ok
test_commit (tests.test_db.TestDatabase) ... ok
test_constructor_schema (tests.test_db.TestDatabase) ... ok
test_copy_table (tests.test_db.TestDatabase) ... ok
test_copy_table_dst_exists (tests.test_db.TestDatabase) ... ok
test_copy_table_no_src (tests.test_db.TestDatabase) ... ok
test_create_drop_tables (tests.test_db.TestDatabase) ... ok
test_create_table_from (tests.test_db.TestDatabase) ... ok
test_empty_table (tests.test_db.TestDatabase) ... ok
test_export_csv (tests.test_db.TestDatabase) ... ok
test_export_csv_bad_path (tests.test_db.TestDatabase) ... ok
test_export_csv_columns (tests.test_db.TestDatabase) ... ok
test_export_csv_file (tests.test_db.TestDatabase) ... ok
test_export_csv_missing_table (tests.test_db.TestDatabase) ... ok
test_export_csv_no_headers (tests.test_db.TestDatabase) ... ok
test_isempty (tests.test_db.TestDatabase) ... ok
test_isempty_missing_table (tests.test_db.TestDatabase) ... ok
test_missing_detach (tests.test_db.TestDatabase) ... ok
test_multiple_attach (tests.test_db.TestDatabase) ... ok
test_multiple_detach (tests.test_db.TestDatabase) ... ok
test_num_rows (tests.test_db.TestDatabase) ... ok
test_num_rows_missing_table (tests.test_db.TestDatabase) ... ok
test_placeholders (tests.test_db.TestDatabase) ... ok
test_schema (tests.test_db.TestDatabase) ... ok
test_schema_empty (tests.test_db.TestDatabase) ... ok
test_table_exists (tests.test_db.TestDatabase) ... ok
test_table_exists_empty (tests.test_db.TestDatabase) ... ok
test_table_exists_not (tests.test_db.TestDatabase) ... ok
test_table_info (tests.test_db.TestDatabase) ... ok
test_table_info_missing_table (tests.test_db.TestDatabase) ... ok
test_tables (tests.test_db.TestDatabase) ... ok
test_tables_empty (tests.test_db.TestDatabase) ... ok
test_tables_setter (tests.test_db.TestDatabase) ... ok
test_where (tests.test_db.TestDatabase) ... ok
test_table (tests.test_fmt.TestFmt) ... ok
test_table_bad_columns (tests.test_fmt.TestFmt) ... ok
test_table_bad_rows (tests.test_fmt.TestFmt) ... ok
test_table_columns (tests.test_fmt.TestFmt) ... ok
test_abspath (tests.test_fs.TestFs) ... ok
test_abspath_homedir (tests.test_fs.TestFs) ... ERROR
test_basename (tests.test_fs.TestFs) ... ok
test_cd (tests.test_fs.TestFs) ... ok
test_cp (tests.test_fs.TestFs) ... ok
test_cp_dir (tests.test_fs.TestFs) ... ok
test_cp_no_file (tests.test_fs.TestFs) ... ok
test_cp_over_dir (tests.test_fs.TestFs) ... ok
test_cp_overwrite (tests.test_fs.TestFs) ... ok
test_dirname (tests.test_fs.TestFs) ... ok
test_exists (tests.test_fs.TestFs) ... ok
test_is_subdir (tests.test_fs.TestFs) ... ok
test_is_subdir_not_subdir (tests.test_fs.TestFs) ... ok
test_isdir (tests.test_fs.TestFs) ... ok
test_isexe (tests.test_fs.TestFs) ... ok
test_isfile (tests.test_fs.TestFs) ... ok
test_ls (tests.test_fs.TestFs) ... ok
test_ls_abspaths (tests.test_fs.TestFs) ... ok
test_ls_bad_path (tests.test_fs.TestFs) ... ok
test_ls_empty_dir (tests.test_fs.TestFs) ... ok
test_ls_recursive (tests.test_fs.TestFs) ... ok
test_ls_single_file (tests.test_fs.TestFs) ... ok
test_lsdirs (tests.test_fs.TestFs) ... ok
test_lsdirs_bad_path (tests.test_fs.TestFs) ... ok
test_lsdirs_recursive (tests.test_fs.TestFs) ... ok
test_lsdirs_single_file (tests.test_fs.TestFs) ... ok
test_lsfiles (tests.test_fs.TestFs) ... ok
test_lsfiles_bad_path (tests.test_fs.TestFs) ... ok
test_lsfiles_recursive (tests.test_fs.TestFs) ... ok
test_lsfiles_single_file (tests.test_fs.TestFs) ... ok
test_mkdir (tests.test_fs.TestFs) ... ok
test_mkdir_exists (tests.test_fs.TestFs) ... ok
test_mkdir_parents (tests.test_fs.TestFs) ... ok
test_mkopen (tests.test_fs.TestFs) ... ok
test_path (tests.test_fs.TestFs) ... ok
test_path_homedir (tests.test_fs.TestFs) ... ERROR
test_pwd (tests.test_fs.TestFs) ... ok
test_read (tests.test_fs.TestFs) ... ok
test_read_empty_file (tests.test_fs.TestFs) ... ok
test_read_ignore_comments (tests.test_fs.TestFs) ... ok
test_read_ignore_comments_no_rstrip (tests.test_fs.TestFs) ... ok
test_read_no_rstrip (tests.test_fs.TestFs) ... ok
test_rm (tests.test_fs.TestFs) ... ok
test_rm_glob (tests.test_fs.TestFs) ... ok
test_colourise (tests.test_io.TestIO) ... ok
test_debug (tests.test_io.TestIO) ... ok
test_error (tests.test_io.TestIO) ... ok
test_fatal (tests.test_io.TestIO) ... ok
test_fatal_status (tests.test_io.TestIO) ... ok
test_info (tests.test_io.TestIO) ... ok
test_pprint (tests.test_io.TestIO) ... ok
test_printf (tests.test_io.TestIO) ... ok
test_prof (tests.test_io.TestIO) ... ok
test_warn (tests.test_io.TestIO) ... ok
test_exit (tests.test_lab.TestLabm8) ... ok
test_flatten (tests.test_lab.TestLabm8) ... ok
test_is_dict (tests.test_lab.TestLabm8) ... ok
test_is_dict_num (tests.test_lab.TestLabm8) ... ok
test_is_dict_seq (tests.test_lab.TestLabm8) ... ok
test_is_dict_str (tests.test_lab.TestLabm8) ... ok
test_is_python3 (tests.test_lab.TestLabm8) ... ok
test_is_seq (tests.test_lab.TestLabm8) ... ok
test_is_seq_dict (tests.test_lab.TestLabm8) ... ok
test_is_seq_num (tests.test_lab.TestLabm8) ... ok
test_is_seq_str (tests.test_lab.TestLabm8) ... ok
test_is_str (tests.test_lab.TestLabm8) ... ok
test_is_str_dict (tests.test_lab.TestLabm8) ... ok
test_is_str_num (tests.test_lab.TestLabm8) ... ok
test_is_str_seq (tests.test_lab.TestLabm8) ... ok
test_escape (tests.test_latex.TestLatex) ... ok
test_table (tests.test_latex.TestLatex) ... ok
test_table_bad_columns (tests.test_latex.TestLatex) ... ok
test_table_bad_rows (tests.test_latex.TestLatex) ... ok
test_table_columns (tests.test_latex.TestLatex) ... ok
test_write_table_body (tests.test_latex.TestLatex) ... ok
test_write_table_body_headers (tests.test_latex.TestLatex) ... ok
test_write_table_body_headers_no_fmt (tests.test_latex.TestLatex) ... ok
test_write_table_body_headers_no_hline (tests.test_latex.TestLatex) ... ok
test_write_table_body_hlines (tests.test_latex.TestLatex) ... ok
test_make (tests.test_make.TestMake) ... ok
test_make_bad_target (tests.test_make.TestMake) ... ok
test_make_clean (tests.test_make.TestMake) ... ok
test_make_fail (tests.test_make.TestMake) ... ok
test_ceil (tests.test_math.TestMath) ... ok
test_ceil_bad_params (tests.test_math.TestMath) ... ok
test_confinterval_123_array (tests.test_math.TestMath) ... ok
test_confinterval_all_same (tests.test_math.TestMath) ... ok
test_confinterval_array_mean (tests.test_math.TestMath) ... ok
test_confinterval_c50 (tests.test_math.TestMath) ... ok
test_confinterval_empty_array (tests.test_math.TestMath) ... ok
test_confinterval_error_only (tests.test_math.TestMath) ... ok
test_confinterval_normal_dist (tests.test_math.TestMath) ... ok
test_confinterval_single_item_array (tests.test_math.TestMath) ... ok
test_filter_iqr (tests.test_math.TestMath) ... ok
test_floor (tests.test_math.TestMath) ... ok
test_floor_bad_params (tests.test_math.TestMath) ... ok
test_geomean (tests.test_math.TestMath) ... ok
test_geomean_empty_array (tests.test_math.TestMath) ... ok
test_geomean_single_item_array (tests.test_math.TestMath) ... ok
test_mean (tests.test_math.TestMath) ... ok
test_mean_empty_array (tests.test_math.TestMath) ... ok
test_mean_single_item_array (tests.test_math.TestMath) ... ok
test_median (tests.test_math.TestMath) ... ok
test_median_empty_array (tests.test_math.TestMath) ... ok
test_median_single_item_array (tests.test_math.TestMath) ... ok
test_range_123_array (tests.test_math.TestMath) ... ok
test_range_empty_array (tests.test_math.TestMath) ... ok
test_range_single_item_array (tests.test_math.TestMath) ... ok
test_sqrt (tests.test_math.TestMath) ... ok
test_sqrt_4 (tests.test_math.TestMath) ... ok
test_stdev_123_array (tests.test_math.TestMath) ... ok
test_stdev_empty_array (tests.test_math.TestMath) ... ok
test_stdev_single_item_array (tests.test_math.TestMath) ... ok
test_variance_123_array (tests.test_math.TestMath) ... ok
test_variance_empty_array (tests.test_math.TestMath) ... ok
test_variance_single_item_array (tests.test_math.TestMath) ... ok
test_arff2csv (tests.test_ml.TestML) ... ok
test_classifier (tests.test_ml.TestML) ... ok
test_classifier_basename (tests.test_ml.TestML) ... ok
test_csv2arff (tests.test_ml.TestML) ... ok
test_dataset_folds (tests.test_ml.TestML) ... ok
test_dataset_len (tests.test_ml.TestML) ... ok
test_import_foreign (tests.test_modules.TestModules) ... ok
test_import_foreign_fail (tests.test_modules.TestModules) ... ok
test_anonymous_timer (tests.test_prof.TestProf) ... ok
test_named_timer (tests.test_prof.TestProf) ... ok
test_new (tests.test_prof.TestProf) ... ok
test_reset (tests.test_prof.TestProf) ... ok
test_reset_bad_name_error (tests.test_prof.TestProf) ... ok
test_stop_bad_name_error (tests.test_prof.TestProf) ... ok
test_stop_twice_error (tests.test_prof.TestProf) ... ok
test_unique_error (tests.test_prof.TestProf) ... ok
test_ScpError (tests.test_system.TestSystem) ... ok
test_echo (tests.test_system.TestSystem) ... ok
test_echo_append (tests.test_system.TestSystem) ... ok
test_echo_kwargs (tests.test_system.TestSystem) ... ok
test_isprocess (tests.test_system.TestSystem) ... ok
test_name (tests.test_system.TestSystem) ... ok
test_pid (tests.test_system.TestSystem) ... ok
test_run (tests.test_system.TestSystem) ... ok
test_run_timeout (tests.test_system.TestSystem) ... ok
test_scp (tests.test_system.TestSystem) ... ok
test_scp_bad_dst (tests.test_system.TestSystem) ... ok
test_scp_bad_dst_permission (tests.test_system.TestSystem) ... ok
test_scp_bad_host (tests.test_system.TestSystem) ... ok
test_scp_bad_path (tests.test_system.TestSystem) ... ok
test_scp_bad_src (tests.test_system.TestSystem) ... ok
test_scp_no_scp (tests.test_system.TestSystem) ... ok
test_scp_user (tests.test_system.TestSystem) ... ok
test_sed (tests.test_system.TestSystem) ... ERROR
test_sed_fail_no_file (tests.test_system.TestSystem) ... ok
test_subprocess_stderr (tests.test_system.TestSystem) ... ok
test_subprocess_stdout (tests.test_system.TestSystem) ... ok
test_subprocess_timeout (tests.test_system.TestSystem) ... ok
test_subprocess_timeout_pass (tests.test_system.TestSystem) ... ok
test_which (tests.test_system.TestSystem) ... ok
test_which_path (tests.test_system.TestSystem) ... ok
test_diff (tests.test_text.TestText) ... ok
test_levenshtein (tests.test_text.TestText) ... ok
test_truncate (tests.test_text.TestText) ... ok
test_truncate_bad_maxchar (tests.test_text.TestText) ... ok
test_now (tests.test_time.TestTime) ... ok
test_nowstr (tests.test_time.TestTime) ... ok
test_strfmt (tests.test_time.TestTime) ... ok

======================================================================
ERROR: test_abspath_homedir (tests.test_fs.TestFs)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/cec/src/labm8/tests/test_fs.py", line 47, in test_abspath_homedir
    re.search("^(/home).*", fs.abspath("~", "foo")).group(1))
AttributeError: 'NoneType' object has no attribute 'group'

======================================================================
ERROR: test_path_homedir (tests.test_fs.TestFs)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/cec/src/labm8/tests/test_fs.py", line 35, in test_path_homedir
    re.search("^(/home).*", fs.path("~", "foo")).group(1))
AttributeError: 'NoneType' object has no attribute 'group'

======================================================================
ERROR: test_sed (tests.test_system.TestSystem)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/cec/src/labm8/tests/test_system.py", line 101, in test_sed
    system.sed("Hello", "Goodbye", "/tmp/labm8.tmp")
  File "/Users/cec/src/labm8/labm8/system.py", line 197, in sed
    raise SubprocessError("Sed command failed!")
SubprocessError: Sed command failed!

----------------------------------------------------------------------
Ran 210 tests in 1.091s

FAILED (errors=3)
[DEBUG ] Storing cache '/tmp/labm8.cache.json'
[DEBUG ] Storing cache '/Users/cec/src/labm8/tests/data/jsoncache.json'
```

**Comment by ChrisCummins** [comment]
Fixed.
